site_name: Baiye Space
site_description: Baiye's Personal Space
site_author: Huabo He
site_url: https://baiyyee.github.io

repo_name: baiyyee/WeTest
repo_url: https://github.com/baiyyee/WeTest

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: 浅色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: 暗黑模式
  font:
    text: Noto Serif Simplified Chinese
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  homepage: https://baiyyee.github.io
  generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/baiyyee
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/hehuabo/wetest
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/WeTest
    - icon: fontawesome/solid/paper-plane
      link: mailto:<hhbstar@hotmail.com>

  analytics:
    provider: google
    property: G-3SXG4P8HT5

copyright: >
  Copyright &copy; 2022 Huabo He

nav:
  - 开源:
      - WeTest: project/wetest.md
      - TestBase: project/testbase.md

  - 技术栈:
      - 编程语言:
          - python: full-stack/coding/python.md
          - mysql: full-stack/coding/mysql.md
          - linux: full-stack/coding/linux.md
          - java: full-stack/coding/java.md
          - go: full-stack/coding/go.md
          - regex: full-stack/coding/regex.md
          - powershell: full-stack/coding/powershell.md
          - html: full-stack/coding/html.md
          - javascript: full-stack/coding/javascript.md
          - css: full-stack/coding/css.md

      - 测试框架:
          - pytest: full-stack/framework/pytest.md
          - playwright: full-stack/framework/playwright.md
          - airtest: full-stack/framework/airtest.md
          - allure: full-stack/framework/allure.md
          - fastapi: full-stack/framework/fastapi.md
          - testng: full-stack/framework/testng.md
          - vue: full-stack/framework/vue.md

      - CI/CD:
          - cicd: full-stack/cicd/cicd.md
          - git: full-stack/cicd/git.md
          - docker: full-stack/cicd/docker.md
          - github: full-stack/cicd/github.md
          - gitlab: full-stack/cicd/gitlab.md
          - jenkins: full-stack/cicd/jenkins.md
          - build: full-stack/cicd/build.md

      - 环境监控:
          - sentry: full-stack/monitor/sentry.md
          - grafana: full-stack/monitor/grafana.md

      - 数据分析:
          - pandas: full-stack/data-analysis/pandas.md
          - numpy: full-stack/data-analysis/numpy.md

      - 压力测试:
          - wrk: full-stack/stress/wrk.md
          - locust: full-stack/stress/locust.md
          - jmeter: full-stack/stress/jmeter.md
          - loadrunner: full-stack/stress/loadrunner.md

      - 常用工具:
          - Python Package: full-stack/tool/python-package.md
          - markdown: full-stack/tool/markdown.md
          - wsl: full-stack/tool/wsl.md
          - pypi: full-stack/tool/pypi.md
          - adb: full-stack/tool/adb.md
          - fiddler: full-stack/tool/fiddler.md
          - postman: full-stack/tool/postman.md
          - redis: full-stack/tool/redis.md
          - rabbitmq: full-stack/tool/rabbitmq.md
          - SonarQube: full-stack/tool/sonarqube.md
          - figma: full-stack/tool/figma.md
          - nginx: full-stack/tool/nginx.md
          - sqlite: full-stack/tool/sqlite.md
          - maven: full-stack/tool/maven.md

      - 最佳实践:
          - 设计模式: full-stack/best-practices/design-pattern.md

      - Wiki:
          - 网络: full-stack/wiki/network.md

      - 算法:
          - Algorithm: full-stack/algorithm/algorithm.md

  - 解决方案:
      - 思路:
          - xxx: tsg/xxx.md

      - 代码:
          - xxx: tsg/xxx.md

      - 工具:
          - git: tsg/git.md
          - pytest: tsg/pytest.md

  - 工作笔记:
      - 配置:
          - 固定配置:
              - .pypirc: notes/config/pypirc.md
              - .zshrc: notes/config/zshrc.md
              - pip.conf: notes/config/pip.md
              - source.list: notes/config/apt-source-list.md
              - settings.json: notes/config/vscode-settings.md

          - 配置样例:
              - Dockerfile: notes/demo/dockerfile.md
              - Docker-compose.yml: notes/demo/docker-compose-yml.md
              - Jenkinsfile: notes/demo/jenkinsfile.md
              - pyproject.toml: notes/demo/pyproject-toml.md
              - setup.py: notes/demo/setup-py.md
              - pytest.ini: notes/demo/pytest-ini.md
              - test.http: notes/demo/restclient-vscode.md

      - SOP:
          - Git Flow: notes/sop/git-flow.md
          - Test Plan: notes/sop/test-plan.md
          - Test Case: notes/sop/test-case.md
          - Test Issue: notes/sop/test-issue.md
          - Test Report: notes/sop/test-report.md
          - Test Review: notes/sop/test-review.md
          - Test Manager: notes/sop/test-manager.md
          - Automated Testing: notes/sop/test-automated.md

      - 用户指导:
          - 如何快速上手 Mac OS?: notes/guideline/how-to-use-mac-os.md
          - 如何通过硬盘安装Win系统?: notes/guideline/how-to-install-win-os.md
          - 如何快速搭建一个个人网站?: notes/guideline/how-to-build-a-personal-website.md
          - 如何将python文件打包成.exe?: notes/guideline/how-to-create-standalone-executables-for-python.md

      - 工具:
          - scoop: notes/tool/scoop.md

      - Tips:
          - tips: notes/tips/tips.md

  - 收藏夹:
      - 教程: favorites/guidelines.md
      - 工具: favorites/tool.md
      - 网站: favorites/site.md
      - 文章: favorites/article.md

  - 白夜:
      - 清单: baiye/list.md
      - 诗集: baiye/poetry.md
      - 摘抄本: baiye/reference.md

  - 关于我: about.md
